[package]
name = "ratefy-cli"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
ratefy-lib = { path = "../ratefy-lib" }
ratefy-menu = { path = "../ratefy-menu" }
rust_decimal = "1"
