name: CI

on: [push, pull_request]

jobs:
  test:
    name: Rust (stable) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mise
        run: |
          curl https://mise.jdx.dev/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install tools with mise
        run: mise install

      - name: Fallback install of Lefthook if not available
        run: |
          if ! command -v lefthook &> /dev/null; then
            echo "Lefthook not found, installing latest release from GitHub..."
            LATEST=$(curl -s https://api.github.com/repos/evilmartians/lefthook/releases/latest | grep browser_download_url | grep "$(uname)" | grep "$(uname -m)" | grep -v .sig | cut -d '"' -f 4)
            curl -L "$LATEST" | tar xz
            chmod +x lefthook
            sudo mv lefthook /usr/local/bin/
          fi

      - name: Run pre-commit hooks
        run: lefthook run pre-commit --all-files
