name: CI

on: [push, pull_request]

jobs:
  test:
    name: Rust (stable) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mise
        run: |
          curl https://mise.jdx.dev/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install tools with mise
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          mise install

      - name: Run pre-commit hooks (Lefthook)
        run: lefthook run pre-commit --all-files
