name: CI

on: [push, pull_request]

jobs:
  test:
    name: Rust (stable) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mise and update PATH
        run: |
          curl https://mise.jdx.dev/install.sh | bash
          export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
          mise install

      - name: Run pre-commit hooks
        run: lefthook run pre-commit --all-files
